# Generated by Django 4.2.5 on 2023-10-09 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='film',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
